# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Delete Package root-library
      uses: actions/delete-package-versions@v2.0.1
      with:
        package-name: 'com.dongkap.root-library'
        token: ${{ github.token }}
        num-old-versions-to-delete: 0
        min-versions-to-keep: 0
    - name: Delete Package satpol-dto
      uses: actions/delete-package-versions@v2.0.1
      with:
        package-name: 'com.dongkap.satpol-dto'
        token: ${{ github.token }}
        num-old-versions-to-delete: 0
        min-versions-to-keep: 0
    - name: Delete Package satpol-common
      uses: actions/delete-package-versions@v2.0.1
      with:
        package-name: 'com.dongkap.satpol-common'
        token: ${{ github.token }}
        num-old-versions-to-delete: 0
        min-versions-to-keep: 0
    - name: Delete Package satpol-feign
      uses: actions/delete-package-versions@v2.0.1
      with:
        package-name: 'com.dongkap.satpol-feign'
        token: ${{ github.token }}
        num-old-versions-to-delete: 0
        min-versions-to-keep: 0
    - name: Publish to GitHub Packages
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
